#!/usr/bin/python
# -*- coding: UTF-8 -*-

#斐波那契数列（Fibonacci sequence），又称黄金分割数列，指的是这样一个数列：0、1、1、2、3、5、8、13、21、34、……。
#在数学上，费波那契数列是以递归的方法来定义：
#学习是用python的经典递归

 
def fib(n):
    a,b = 1,1
    for i in range(n-1):
        a,b = b,a+b      #python挺方便的,直接通过这个方式交换值,不需要引用另外的变量,比C简洁一些
    return a
 
# 输出了第10个斐波那契数列
print (fib(10))
