#!/usr/bin/python
# -*- coding: UTF-8 -*-

#九九乘法表


for i in range(1,10):
	for j in range(1,10):
		if(i>=j):
			#print(i+1 * s+1 = (i+1)*(j+1),end='')
			#print("%d*%d=%d"%(i+1,j+1,(i+1)*(j+1)))
			print("%d*%d=%d "%(j,i,i*j),end='')
			#print("%d*%d= %d"%((i+i),(j+1),((i+1)*(j+1))))
			if(i==j):
				print()
