#!/usr/bin/python
# -*- coding: UTF-8 -*-

#输入三个整数x,y,z，请把这三个数由小到大输出。
#直接利用了列表的排序方法，如果不利用列表的排序，怎么做呢？

l = []  #定义l为列表,不是说python是弱语言吗,为什么还要定义列表呢？
for i in range(3):
    x = int(input('integer:\n'))
    l.append(x)
l.sort()
print (l)

